### ISSUE TITLE
Integrate with skeuomorph monomorphic version

### ISSUE THREAD

**Issue by rafaparadela** [higherkindness/compendium#12]
Create a functionality to execute the schema transformation from skeuomorph from the API and then store the result in Catamorph.

[**yago**] Here I'm gonna list some issues related with this one, checking them if they're done
- [x] Change DB service to accept Metadata. Done here: #54
- [x] Create parsing Service. Done here: #54 
- [ ] Parsing to Protobuf from whatever. Issue: #97
- [ ] Parsing to Avro from whatever. Issue: #100
- [ ] Parsing to Openapi from whatever. Issue: #99
- [ ] Parsing to Mu from whatever. Issue: #98 Partially done here: #54 
- [x] Use Resource for Protobuf temporal file. Issue: #101
- [ ] Store new Protocol in DB and Storage service. Issue: #102
- [ ] Test for parsing endpoint. Issue: #103

**Comment by Yawolf** [comment]
I'm closing this huge Task in favor of these others more simple:
- Generate Protobuf from any other IDL #97
- Generate Mu from any other IDL #98
- Generate Openapi from any other IDL #99
- Generate Avro from any other IDL #100
- Use Resource for temporal file #101
- Storage service for new Protocols after Parsing #102
- Tests for parsing Endpoint #103
